### ISSUE TITLE
log downloading does not work when running packaged exe

### ISSUE THREAD

**Issue by A-Baji** [A-Baji/discordAI#50]
```
PS D:\discordai> .\discordai.exe model create -c 1255993340218839111 -u adibiswat --ttime 0
INFO: Exporting chat logs using DiscordChatExporter...
INFO: This may take a few minutes to hours depending on the message count of the channel
INFO: Progress will NOT be saved if cancelled
--------------------------DiscordChatExporter---------------------------
Traceback (most recent call last):
  File "discordai\command_line\command_line.py", line 92, in <module>
  File "discordai\command_line\command_line.py", line 46, in discordai
  File "discordai_modelizer\command_line\command_line.py", line 40, in read_modelizer_args
  File "discordai_modelizer\customize.py", line 58, in create_model
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application
[16060] Failed to execute script 'command_line' due to unhandled exception!
```

**Comment by A-Baji** [comment]
This is because the included version of DiscordChatExporter is only for linux
